server:
  port:
    3817

debug:
  true

spring:
  application:
    name: ren3

  datasource:
      name: test
      url: jdbc:mysql://101.132.185.90/ren3
      username: root
      password: 19980508yjh
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: com.chen.ren3