server:
  port:
    10000

debug:
  true

spring:
  application:
    name: ren3

  datasource:
      name: test
      url: jdbc:mysql://119.23.226.114/ren3
      username: root
      password: baichi82995087
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: com.chen.ren3